### ISSUE TITLE
System.InvalidOperationException: No action for the assembly Weighted Randomizer Net Standard, Version=1.0.3.0

### ISSUE THREAD

**Issue by batonPiotr** [BlueRaja/Weighted-Item-Randomizer-for-C-Sharp#5] opened 2021-01-12 22:41 UTC
I get this error while compiling with Unity 2019.4.17f1 with netstandard 2.0 and IL2CPP:
`System.InvalidOperationException: No action for the assembly Weighted Randomizer Net Standard, Version=1.0.3.0`

This library has been integrated with NuGetForUnity 2.0.1.

**Comment by BlueRaja** [comment] 2021-01-12 23:04
I have no idea what this is, but a quick google search seems to indicate it's not a bug with this library. Do you have reason to believe it is?

**Comment by batonPiotr** [comment] 2021-01-12 23:58
I cannot tell exactly. I was able to compile the code when added as source code, not as a NuGet package. I am able to compile the project with other libraries added through NuGet, so it would rule out the problems with the NuGet Package Manager for Unity.

I think it could be a problem with all these spaces in filenames and paths. Try to rename all of them so it is replaced with `-`, `_` or just plainly write `WeightedRandomizerNetStandard` instead of `Weighted Randomizer Net Standard` etc.

**Comment by Botched135** [comment] 2021-03-25 21:23
The exact same issue happens when you try to use it with .NET Core. Looks like the .dll file is packaged as 'Weighted Randomizer'

**Comment by BlueRaja** [comment] 2021-11-12 21:32
This should be fixed in v2.0. Please let me know if the issue still occurs.

**Closed as completed by BlueRaja** 2021-11-12 21:32 UTC
